title: My Private Site
author: Me
description: > # this means to ignore newlines until "baseurl:"
  This is my private GitHub Pages site.
baseurl: "/private-site"
url: "https://bbangbongg.github.io"
theme: minima

header_pages:
  - proof-diary.md

collections:
  proof-diary:
    output: true
    permalink: /proof-diary/:name/

defaults:
  - scope:
      path: ""
      type: "proof-diary"
    values:
      layout: proof_entry

minima:
  nav_links:
    - title: "Home"
      url: "/private-site/"
    - title: "Proof Diary"
      url: "/private-site/proof-diary/"

# ➕ math rendering
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
