title: My Private Site
author: Me
description: > # this means to ignore newlines until "baseurl:"
  This is my private GitHub Pages site.
baseurl: "/private-site" # repository name
url: "https://bbangbongg.github.io" # your GitHub Pages URL without trailing slash
theme: minima
